/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QASystem;

import Tokenizer.Wordizer;
import Tokenizer.Word;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Van
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_search = new javax.swing.JButton();
        text_result = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_question = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_search.setText("Trả lời");
        Btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_searchActionPerformed(evt);
            }
        });

        text_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_resultActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập câu hỏi vào đây:");

        text_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_questionActionPerformed(evt);
            }
        });

        jLabel2.setText("Kết quả:");

        jLabel3.setText("Lưu ý: Đã có một số câu test trong console, xin mời xem mẫu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_search)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_result, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                            .addComponent(text_question)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(Btn_search)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_resultActionPerformed

    private void text_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_questionActionPerformed

    private void Btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_searchActionPerformed
//        // TODO add your handling code here:
//        text_result.setText(text_question.getText());
//        Wordizer tkn = new Wordizer(text_question.getText());
//        List<Word> tk = tkn.wordize();
//        String str="";
//        for(int i =0;i < tk.size();i++){
//            str +=tk.get(i).word +"--";
//            //System.err.println(tk.get(i).word);
//        }
//        text_result.setText(str);
        // ProceduvalSematic.run("sinh viên nào học môn học ngôn ngữ lập trình và xử lý ngôn ngữ tự nhiên");
        if (text_question.getText().equals("")) {
            return;
        }
        AnswerSystem as = new AnswerSystem(text_question.getText());
        text_result.setText("Xem kết quả ở console");
        as.answer();
    }//GEN-LAST:event_Btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                List<String> questions = new ArrayList<>();
                questions.add("sinh viên nào học môn xử lý ngôn ngữ tự nhiên?");
                questions.add("môn ngôn ngữ lập trình có những sinh viên nào học?");
                questions.add("hãy cho biết sinh viên có mã số mt12002 học môn gì?");
                 questions.add("hãy cho biết sinh viên có mã số sinh viên mt12010 học môn gì?");
                questions.add("môn xử lý ngôn ngữ tự nhiên học phòng nào, ngày nào, học tiết mấy, học mấy tiết?");
                questions.add("sinh viên Phạm Văn hai học môn gì, ngày nào, tiết mấy, phòng học mấy? ");
                questions.add("Sinh viên nào học Môn học NGÔN ngữ lập trình");
                questions.add("Hãy cho biết môn học xử lý ngôn học phòng nào?");// does not have answer
                for (int i = 0; i < questions.size(); i++) {
                    AnswerSystem as = new AnswerSystem(questions.get(i));                   
                    as.answer();
                }
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField text_question;
    private javax.swing.JTextField text_result;
    // End of variables declaration//GEN-END:variables
}
